spring.datasource.url=jdbc:mysql://127.0.0.1:3309/bousselha_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JWT and Mail config (same as docker)
jwt.secret=changeitchangemechangeitchangemechangeitchangeme
app.uploads.dir=./uploads
app.allow-fallback-admin=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krachelfahd@gmail.com
spring.mail.password=qhskeomwpxowwqms
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=krachelfahd@gmail.com

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

